In [1]:
#Type Of Object
#Sequence Object = List,Tuple,set

In [2]:
#User Function

In [3]:
list = [100,200,300]

In [4]:
def function1(a):
    print(a)

In [5]:
function1('Hello')

Hello


In [ ]:
def function1(a):
    print(a)

In [6]:
# Function print, return ???

In [7]:
def function3(x):
    for i in x:
    return (x.upper())
    

In [ ]:
def function4(x):
    return (x.upper())

In [ ]:
list = ['hello','a','greeting']

# Map , Filter and Zip and List

In [8]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
list =[1,2,3,4,5,6,7,8,9,10]

In [11]:
list(range(0,10))

TypeError: 'list' object is not callable

In [12]:
list1 = [100,200,300]

In [13]:
list2 = ['a','b','c']

In [14]:
zip(list1,list2)

In [15]:
for i in zip(list1,list2):
    print(i)

(100, 'a')
(200, 'b')
(300, 'c')


In [17]:
def mutltiply(x):
    return x*2;

In [21]:
for i in map(mutltiply,list1):
    print(i)

200
400
600


In [22]:
# def upper(1): return x.upper()

In [24]:
def upper2(x):return x.upper()
    

In [26]:
upper2('hello')

'HELLO'

# Lambda Function

In [29]:
a = lambda x:x*2

In [31]:
a(3)

6

In [33]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
list(map(lambda x: x * 3,list))

TypeError: 'list' object is not callable

In [41]:
list(map(lambda a: 'OVer 5' if a> 5 else 'normal', list))

TypeError: 'list' object is not callable

In [63]:
# Define your list of numbers
numbers = [1, 3, 7, 9, 4, 5]

# Use map with a lambda function
result = numbers(map(lambda a: 'Over 5' if a > 5 else 'normal', numbers))

print(result)


TypeError: 'list' object is not callable

In [43]:
#Data analysis
#Numpy
#Pandas
#Matiplots
#Seaborn

#Data Science
#sickilearn
#tensorflow

In [42]:
list


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Numpy

In [46]:
!pip install numpy

In [47]:
!pip install padas

ERROR: Could not find a version that satisfies the requirement padas (from versions: none)
ERROR: No matching distribution found for padas


In [48]:
import numpy as np

In [49]:
!pip install pandas

In [50]:
import pandas as pd

# What is array ?? 1 Demenstional Array

In [52]:
numberlist=[1,2,3,4,5]

In [53]:
type(list)

list

In [54]:
np.array(list)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
a =np.array(list)

In [56]:
type(a)

numpy.ndarray

In [57]:
a*4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [58]:
numberlist*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [59]:
a.shape

(10,)

In [62]:
b= np.array([[1,2,3],[4,5,6]]) #List 2

In [64]:
b.shape

(2, 3)

In [65]:
#3D array

In [69]:
c = np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [67]:
c.shape

(3, 3)

In [70]:
c[0]

array([1, 2, 3])

In [71]:
c[0][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [72]:
c[0][2]

3

In [73]:
c[0:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

In [75]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [76]:
np.sort(c,axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Array Create

In [78]:
f = np.full((4,4),'abc')

In [79]:
type(f)

numpy.ndarray

In [80]:
f

array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [82]:
listrange = np.arange(0,10,1)

In [85]:
list(listrange *2)

TypeError: 'list' object is not callable

In [88]:
l=np.linspace(0,10,10)

In [87]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
l

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [91]:
l[l>5]

array([ 5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [92]:
np.random.randint(0,10,(3,3))

array([[4, 6, 7],
       [7, 3, 6],
       [6, 4, 7]])

# What is Pandas

In [93]:
#Two Type of Pandas
#Series ,dataframe

#look like excel ==> row,column(index)
#input / output
#filter Date
#Data Cleaning
#Pivot
#Aggregation 
#Group by
#Join


In [95]:
s = pd.Series(data=[100,200,300],index=['a','b','c'])

In [96]:
s["c"]

300

In [97]:
type(s)

pandas.core.series.Series

In [98]:
dict1 = {
    'apple':100,
    'orange':120,
    'mango':150
}

In [101]:
pd.Series(data = dict1.values(),index=dict1.keys())

apple     100
orange    120
mango     150
dtype: int64

In [103]:
dict1.values()

dict_values([100, 120, 150])

In [104]:
dict1.keys()

dict_keys(['apple', 'orange', 'mango'])

In [105]:
data1=[100,200,300]
index1=['apple','mango','orange']
col=['price']

In [107]:
df = pd.DataFrame(data=data1,index=index1,columns=col)

In [108]:
df.to_csv('first.csv')

In [109]:
df

price
apple     100
mango     200
orange    300

In [110]:
df.to_csv('first.csv')

In [123]:
data2=[[10,20,30],[40,50,60],[70,80,90]]


In [124]:
index2=['apple','mango','orange']

In [125]:
col2=['2012','2013','2014']

In [126]:
df2= pd.DataFrame(data=data2,index=index2,columns=col2)

In [127]:
df2

2012  2013  2014
apple     10    20    30
mango     40    50    60
orange    70    80    90

In [128]:
df2['total']=df2['2012']+df2['2013']+df2['2014']

In [129]:
df2

2012  2013  2014  total
apple     10    20    30     60
mango     40    50    60    150
orange    70    80    90    240

In [130]:
df2['2012']

apple     10
mango     40
orange    70
Name: 2012, dtype: int64

In [131]:
df2['total']

apple      60
mango     150
orange    240
Name: total, dtype: int64

In [132]:
df2.iloc[0]

2012     10
2013     20
2014     30
total    60
Name: apple, dtype: int64

In [133]:
ls

 Volume in drive C is OS
 Volume Serial Number is D215-09A5

 Directory of C:\Users\PyaePhyoAye

07/28/2024  05:51 PM    <DIR>          .
02/05/2024  03:07 PM    <DIR>          ..
07/13/2024  04:18 PM    <DIR>          .anaconda
06/08/2024  05:28 PM                12 .bash_history
07/28/2024  05:53 PM    <DIR>          .conda
07/13/2024  04:19 PM                25 .condarc
07/13/2024  04:18 PM    <DIR>          .continuum
06/08/2024  07:11 PM               161 .gitconfig
07/28/2024  05:50 PM    <DIR>          .ipynb_checkpoints
07/13/2024  04:47 PM    <DIR>          .ipython
07/14/2024  04:04 PM    <DIR>          .jupyter
06/22/2024  06:13 PM                20 .lesshst
06/08/2024  09:57 PM    <DIR>          .ssh
06/08/2024  07:12 PM               689 .viminfo
07/13/2024  04:18 PM    <DIR>          anaconda3
02/05/2024  03:07 PM    <DIR>          Contacts
07/28/2024  05:49 PM            64,051 dataframe_pandas.ipynb
06/15/2024  09:20 PM    <DIR>          Desktop
07/13/2024  04:18 PM    

In [134]:
cd Downloads\

C:\Users\PyaePhyoAye\Downloads


In [135]:
df2.to_csv('first.csv')